import{Product}from"./types";

export const demoProducts:Product[]=[
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1",slug:"macey-country-treat-box",name:"Macey Country Treat Box",short_description:"A hand-picked gift box filled with Macey’s favourites.",description:"A generous £20 treat box including scones, cupcakes, a banana loaf slice and a selection of sweet treats. A lovely ready-to-gift taste of Macey’s Country Bakery.",price_pence:2000,stock:12,is_available:true,is_visible:true,category:"Gift Boxes",image_url:"https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2",slug:"luxury-celebration-cupcakes-6",name:"Luxury Celebration Cupcakes — Box of 6",short_description:"Six beautifully finished cupcakes for a special occasion.",description:"A luxury box of six celebration cupcakes, perfect for birthdays, baby showers, christenings and gifts.",price_pence:1400,stock:12,is_available:true,is_visible:true,category:"Cupcakes",image_url:"https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3",slug:"luxury-celebration-cupcakes-12",name:"Luxury Celebration Cupcakes — Box of 12",short_description:"Twelve beautifully finished cupcakes for larger celebrations.",description:"A luxury box of twelve celebration cupcakes, perfect for birthdays, baby showers, christenings and gifts.",price_pence:2800,stock:8,is_available:true,is_visible:true,category:"Cupcakes",image_url:"https://images.unsplash.com/photo-1519915028121-7d3463d20b13?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4",slug:"classic-cupcakes-6",name:"Classic Cupcakes — Box of 6",short_description:"Six homemade classic cupcakes.",description:"A box of six soft, homemade cupcakes with a classic finish. Ideal for sharing, gifting or a weekend treat.",price_pence:1200,stock:15,is_available:true,is_visible:true,category:"Cupcakes",image_url:"https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5",slug:"classic-cupcakes-12",name:"Classic Cupcakes — Box of 12",short_description:"Twelve homemade classic cupcakes.",description:"A box of twelve soft, homemade cupcakes with a classic finish. Ideal for parties, sharing and celebrations.",price_pence:2200,stock:10,is_available:true,is_visible:true,category:"Cupcakes",image_url:"https://images.unsplash.com/photo-1486427944299-d1955d23e34d?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa6",slug:"mini-banana-loaf",name:"Mini Banana Loaf",short_description:"A personal-sized homemade banana loaf.",description:"Choose Classic Banana, Banana & Chocolate Chip, or Banana & Walnut. Please include your flavour choice in the order notes when ordering.",price_pence:400,stock:20,is_available:true,is_visible:true,category:"Banana Loaves",image_url:"https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg","Nuts"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa7",slug:"large-banana-loaf",name:"Large Banana Loaf",short_description:"A full homemade banana loaf for slicing and sharing.",description:"Choose Classic Banana, Banana & Chocolate Chip, or Banana & Walnut. Please include your flavour choice in the order notes when ordering.",price_pence:800,stock:12,is_available:true,is_visible:true,category:"Banana Loaves",image_url:"https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg","Nuts"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa8",slug:"banana-loaf-slice",name:"Banana Loaf Slice",short_description:"A thick slice of homemade banana loaf.",description:"A generous individual slice of Macey’s homemade banana loaf. Flavour availability changes with each bake.",price_pence:300,stock:24,is_available:true,is_visible:true,category:"Banana Loaves",image_url:"https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg","Nuts"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa9",slug:"enriched-dinner-rolls-9",name:"Homemade Enriched Dinner Rolls — 9",short_description:"Nine soft, fluffy enriched dinner rolls.",description:"Nine homemade rolls made with fresh milk, powdered milk, eggs and butter. Soft, rich and perfect for the family table.",price_pence:750,stock:10,is_available:true,is_visible:true,category:"Dinner Rolls",image_url:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa10",slug:"enriched-dinner-rolls-12",name:"Homemade Enriched Dinner Rolls — 12",short_description:"Twelve soft, fluffy enriched dinner rolls.",description:"Twelve homemade rolls made with fresh milk, powdered milk, eggs and butter. Soft, rich and perfect for the family table.",price_pence:1000,stock:10,is_available:true,is_visible:true,category:"Dinner Rolls",image_url:"https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]},
{id:"11111111-1111-1111-1111-111111111111",slug:"classic-buttermilk-scones",name:"Classic Buttermilk Scones",short_description:"Tender, tall and baked with cultured buttermilk.",description:"Our signature scones: crisp at the edges, cloud-soft within, and finished with a light brush of cream.",price_pence:1450,stock:18,is_available:true,is_visible:true,category:"Scones",image_url:"https://images.unsplash.com/photo-1608198093002-ad4e005484ec?auto=format&fit=crop&w=1200&q=85",allergens:["Gluten","Milk","Egg"]}
];
