"use server";import{revalidatePath}from"next/cache";import{z}from"zod";import{createSupabaseAdminClient,requireAdmin}from"@/lib/supabase/server";
const product=z.object({id:z.string().uuid().optional(),name:z.string().min(2),slug:z.string().regex(/^[a-z0-9-]+$/),category_id:z.string().uuid(),description:z.string().min(10),short_description:z.string().min(5),price_pence:z.coerce.number().int().positive(),stock:z.coerce.number().int().min(0)});
export async function saveProduct(form:FormData){await requireAdmin();const v=product.parse(Object.fromEntries(form)),db=createSupabaseAdminClient(),{id,...rest}=v,values={...rest,is_visible:form.has("is_visible"),is_available:form.has("is_available")};const{error}=id?await db.from("products").update(values).eq("id",id):await db.from("products").insert(values);if(error)throw error;revalidatePath("/shop");revalidatePath("/admin")}
export async function deleteProduct(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("id"));const{error}=await createSupabaseAdminClient().from("products").delete().eq("id",id);if(error)throw error;revalidatePath("/admin");revalidatePath("/shop")}
export async function updateOrder(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("id")),status=z.enum(["paid","preparing","ready","collected","cancelled","refunded"]).parse(form.get("status"));const{error}=await createSupabaseAdminClient().from("orders").update({status}).eq("id",id);if(error)throw error;revalidatePath("/admin")}
export async function saveSlot(form:FormData){await requireAdmin();const starts=z.string().min(1).parse(form.get("starts_at")),ends=z.string().min(1).parse(form.get("ends_at")),capacity=z.coerce.number().int().min(1).parse(form.get("capacity"));const{error}=await createSupabaseAdminClient().from("collection_slots").insert({starts_at:new Date(starts).toISOString(),ends_at:new Date(ends).toISOString(),capacity,is_active:true});if(error)throw error;revalidatePath("/admin")}
export async function deleteSlot(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("id"));const{error}=await createSupabaseAdminClient().from("collection_slots").delete().eq("id",id);if(error)throw error;revalidatePath("/admin")}
export async function savePost(form:FormData){await requireAdmin();const v=z.object({id:z.string().uuid().optional(),title:z.string().min(3),slug:z.string().regex(/^[a-z0-9-]+$/),excerpt:z.string().min(5),content:z.string().min(20)}).parse(Object.fromEntries(form)),db=createSupabaseAdminClient(),{id,...rest}=v,values={...rest,is_published:form.has("is_published"),published_at:new Date().toISOString()};const{error}=id?await db.from("blog_posts").update(values).eq("id",id):await db.from("blog_posts").insert(values);if(error)throw error;revalidatePath("/blog");revalidatePath("/admin")}
export async function deletePost(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("id"));const{error}=await createSupabaseAdminClient().from("blog_posts").delete().eq("id",id);if(error)throw error;revalidatePath("/admin");revalidatePath("/blog")}
export async function uploadImage(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("product_id")),file=z.instanceof(File).refine(f=>f.size<=5_000_000).refine(f=>["image/jpeg","image/png","image/webp"].includes(f.type)).parse(form.get("image")),db=createSupabaseAdminClient(),path=`${id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9.-]/g,"")}`;const{error}=await db.storage.from("product-images").upload(path,file,{contentType:file.type});if(error)throw error;const{data}=db.storage.from("product-images").getPublicUrl(path);await db.from("product_images").insert({product_id:id,storage_path:path,url:data.publicUrl});revalidatePath("/admin");revalidatePath("/shop")}
export async function removeImage(form:FormData){await requireAdmin();const id=z.string().uuid().parse(form.get("id")),path=z.string().min(1).parse(form.get("path")),db=createSupabaseAdminClient();const{error}=await db.storage.from("product-images").remove([path]);if(error)throw error;await db.from("product_images").delete().eq("id",id);revalidatePath("/admin");revalidatePath("/shop")}
