create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','admin');
create type public.order_status as enum ('pending','paid','preparing','ready','collected','cancelled','refunded');
create type public.payment_status as enum ('unpaid','paid','refunded','failed');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,role public.user_role not null default 'customer',full_name text,created_at timestamptz not null default now());
create table public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,sort_order integer not null default 0);
create table public.products(id uuid primary key default gen_random_uuid(),category_id uuid not null references public.categories(id),name text not null,slug text not null unique,short_description text not null,description text not null,price_pence integer not null check(price_pence>0),stock integer not null default 0 check(stock>=0),is_visible boolean not null default false,is_available boolean not null default false,sort_order integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.product_images(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.products(id) on delete cascade,storage_path text not null unique,url text not null,alt_text text not null default '',sort_order integer not null default 0);
create table public.allergens(id uuid primary key default gen_random_uuid(),name text not null unique);
create table public.product_allergens(product_id uuid references public.products(id) on delete cascade,allergen_id uuid references public.allergens(id) on delete cascade,primary key(product_id,allergen_id));
create table public.collection_slots(id uuid primary key default gen_random_uuid(),starts_at timestamptz not null,ends_at timestamptz not null,capacity integer not null check(capacity>0),booked integer not null default 0 check(booked>=0),is_active boolean not null default true,check(ends_at>starts_at),check(booked<=capacity));
create table public.orders(id uuid primary key default gen_random_uuid(),order_number bigint generated always as identity unique,user_id uuid references auth.users(id) on delete set null,status public.order_status not null default 'pending',payment_status public.payment_status not null default 'unpaid',customer_email text,collection_slot_id uuid not null references public.collection_slots(id),collection_starts_at timestamptz not null,total_pence integer not null check(total_pence>=0),currency text not null default 'gbp',stripe_checkout_session_id text unique,stripe_payment_intent_id text unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,unit_price_pence integer not null check(unit_price_pence>0),quantity integer not null check(quantity>0),allergens text[] not null default '{}');
create table public.blog_posts(id uuid primary key default gen_random_uuid(),title text not null,slug text not null unique,excerpt text not null,content text not null,is_published boolean not null default false,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.stripe_events(id text primary key,type text not null,processed_at timestamptz,created_at timestamptz not null default now());

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=auth.uid() and role='admin')$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id) values(new.id);return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create view public.products_public with(security_invoker=true) as
select p.id,p.slug,p.name,p.short_description,p.description,p.price_pence,p.stock,p.is_available,p.is_visible,p.sort_order,c.name category,(select pi.url from public.product_images pi where pi.product_id=p.id order by pi.sort_order limit 1) image_url,coalesce((select array_agg(a.name order by a.name) from public.product_allergens pa join public.allergens a on a.id=pa.allergen_id where pa.product_id=p.id),'{}') allergens
from public.products p join public.categories c on c.id=p.category_id where p.is_visible=true;
create view public.available_collection_slots with(security_invoker=true) as select * from public.collection_slots where is_active=true and starts_at>now() and booked<capacity;

alter table public.profiles enable row level security;alter table public.categories enable row level security;alter table public.products enable row level security;alter table public.product_images enable row level security;alter table public.allergens enable row level security;alter table public.product_allergens enable row level security;alter table public.collection_slots enable row level security;alter table public.orders enable row level security;alter table public.order_items enable row level security;alter table public.blog_posts enable row level security;alter table public.stripe_events enable row level security;
create policy "profile own read" on public.profiles for select using(id=auth.uid() or public.is_admin());
create policy "public categories read" on public.categories for select using(true);
create policy "public visible products read" on public.products for select using(is_visible or public.is_admin());
create policy "public product images read" on public.product_images for select using(true);
create policy "public allergens read" on public.allergens for select using(true);create policy "public product allergens read" on public.product_allergens for select using(true);
create policy "public active slots read" on public.collection_slots for select using(is_active and starts_at>now() or public.is_admin());
create policy "customers own orders read" on public.orders for select using(user_id=auth.uid() or public.is_admin());
create policy "customers own order items read" on public.order_items for select using(exists(select 1 from public.orders o where o.id=order_id and(o.user_id=auth.uid() or public.is_admin())));
create policy "public posts read" on public.blog_posts for select using(is_published or public.is_admin());
create policy "admins manage categories" on public.categories for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage products" on public.products for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage images" on public.product_images for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage allergens" on public.allergens for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage product allergens" on public.product_allergens for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage slots" on public.collection_slots for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage orders" on public.orders for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage order items" on public.order_items for all using(public.is_admin()) with check(public.is_admin());create policy "admins manage posts" on public.blog_posts for all using(public.is_admin()) with check(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('product-images','product-images',true,5000000,array['image/jpeg','image/png','image/webp']);
create policy "public product image access" on storage.objects for select using(bucket_id='product-images');
create policy "admin product image insert" on storage.objects for insert to authenticated with check(bucket_id='product-images' and public.is_admin());
create policy "admin product image delete" on storage.objects for delete to authenticated using(bucket_id='product-images' and public.is_admin());

create or replace function public.complete_paid_order(p_order_id uuid,p_payment_intent text,p_customer_email text) returns void language plpgsql security definer set search_path='' as $$declare v_slot uuid;v_status public.payment_status;rec record;begin select collection_slot_id,payment_status into v_slot,v_status from public.orders where id=p_order_id for update;if v_status='paid' then return;end if;for rec in select * from public.order_items where order_id=p_order_id loop update public.products set stock=stock-rec.quantity where id=rec.product_id and stock>=rec.quantity;if not found then raise exception 'insufficient stock';end if;end loop;update public.collection_slots set booked=booked+1 where id=v_slot and booked<capacity;if not found then raise exception 'slot full';end if;update public.orders set status='paid',payment_status='paid',stripe_payment_intent_id=p_payment_intent,customer_email=p_customer_email,updated_at=now() where id=p_order_id;end$$;

insert into public.categories(name,slug,sort_order) values('Scones','scones',1),('Loaves','loaves',2),('Cakes','cakes',3),('Cookies','cookies',4);
insert into public.allergens(name) values('Gluten'),('Milk'),('Egg'),('Soya'),('Nuts'),('Peanuts'),('Sesame');
